#!/usr/bin/env node
// Regenerate spec/vectors/*.json from the reference implementation.
// The vectors are what a second implementation checks itself against, so every entry carries its inputs, the
// intermediate hashes an implementer can compare against while debugging, and the final expected value.
// 从参考实现重新生成规范测试向量。向量是第二个实现用来自检的东西，因此每条都带输入、可在调试时逐步对照的
// 中间哈希，以及最终的期望值。
import { writeFileSync, mkdirSync } from 'node:fs'
import { canonicalJSON } from '../sdk/src/canon.js'
import { keccak256, toHex, utf8ToBytes } from '../sdk/src/abi.js'
import * as sig from '../sdk/src/sig.js'

const HOLDER_KEY = '0x' + '11'.repeat(32)
const SIGNER_KEY = '0x' + '22'.repeat(32)
const CONSUMER_KEY = '0x' + '33'.repeat(32)
const HUB = '0xe61A9C7213a6Aa616C246a2B569e555B417b25ee'
const ESCROW = '0x00000000000000000000000000000000000E5c70'
const CONTAINER = '0x86DDaEF00401E3F10418398D67D7189fc458eA95'
const CHAIN_ID = 56
const k = (s) => toHex(keccak256(utf8ToBytes(s)))

mkdirSync(new URL('../spec/vectors/', import.meta.url), { recursive: true })
const write = (name, obj) => {
  writeFileSync(new URL(`../spec/vectors/${name}`, import.meta.url), JSON.stringify(obj, null, 2) + '\n')
  console.log(' wrote spec/vectors/' + name)
}
const note = 'Generated by scripts/gen-vectors.mjs. Every field is an input or an expected output; nothing here is advisory. / 由 scripts/gen-vectors.mjs 生成，每个字段要么是输入要么是期望输出，没有一条是参考性的。'

// ---------- canonicalJSON (TAP-21 §3.3) ----------
const canonPositive = [
  { name: 'keys sort by UTF-16 code unit, recursively', input: { b: 1, a: { d: 4, c: 3 } } },
  { name: 'digits sort before uppercase, uppercase before lowercase', input: { 10: 1, 2: 1, A: 1, a: 1, 1: 1 } },
  { name: 'array order is preserved', input: { xs: [3, 1, 2], ys: [{ b: 1, a: 2 }] } },
  { name: 'no whitespace anywhere', input: { a: [1, { b: 'c' }] } },
  { name: 'strings escape as in JSON.stringify', input: { s: 'a"b\\c\nd\te' } },
  { name: 'non-ASCII is emitted literally, not escaped', input: { s: '中文 😀' } },
  { name: 'a surrogate pair sorts by its UTF-16 units, so z precedes an emoji', input: { '😀': 1, z: 2 } },
  { name: 'fractional numbers use the shortest round-trip form', input: { a: 0.1, b: 1.5e-7, c: -2.25 } },
  { name: 'the safe-integer boundary is allowed', input: { n: 9007199254740991, m: -9007199254740991 } },
  { name: 'amounts travel as strings, which is exact at any size', input: { amount: '123456789012345678901234567890' } },
  { name: 'empty object and empty array', input: { o: {}, a: [] } },
  { name: 'null is a value, not an absence', input: { a: null } },
]
const canonNegative = [
  { name: 'duplicate key in the same object', text: '{"a":1,"a":2}', expect: 'CANON_INVALID' },
  { name: 'duplicate key nested', text: '{"o":{"k":1,"k":2}}', expect: 'CANON_INVALID' },
  { name: 'duplicate key where one form is escaped', text: '{"\\u0061":1,"a":2}', expect: 'CANON_INVALID' },
  { name: '__proto__ as an own key', text: '{"__proto__":{}}', expect: 'CANON_INVALID' },
  { name: 'constructor as an own key', text: '{"constructor":1}', expect: 'CANON_INVALID' },
  { name: 'prototype as an own key', text: '{"prototype":1}', expect: 'CANON_INVALID' },
  { name: 'integer past 2^53', value: 9007199254740993, expect: 'CANON_INVALID' },
  { name: 'integer written in exponent form past 2^53', value: 1e21, expect: 'CANON_INVALID' },
  { name: 'negative zero', valueExpr: '-0', expect: 'CANON_INVALID' },
  { name: 'NaN', valueExpr: 'NaN', expect: 'CANON_INVALID' },
  { name: 'Infinity', valueExpr: 'Infinity', expect: 'CANON_INVALID' },
  { name: 'a value carrying toJSON()', valueExpr: 'new Date(0)', expect: 'CANON_INVALID' },
]
write('tap-21-canon.json', {
  tap: 'TAP-21 §3.3', note,
  rule: 'JCS (RFC 8785) plus: no duplicate keys, no NaN/Infinity/-0, no integer outside +-(2^53-1), no __proto__/constructor/prototype, no lone UTF-16 surrogates, and no host-language hook such as toJSON().',
  positive: canonPositive.map((c) => ({ ...c, canonical: canonicalJSON(c.input), keccak256: k(canonicalJSON(c.input)) })),
  negative: canonNegative,
})

// ---------- TAP-21 response envelope ----------
const envCases = [
  { name: 'free method, empty params, ok', id: 'req-1', method: 'blockNumber', params: {}, ok: true, body: { blockNumber: 123456789 }, ts: 1789000000 },
  { name: 'paid method with params, ok', id: 'req-2', method: 'circuitHolder', params: { circuits: '0x50A994e71615474B55559FF4f500928fbc339DD9', tokenId: '4246' }, ok: true, body: { holder: '0x571d447f4f24688eC35Ccf07f1D6993655F6aF15' }, ts: 1789000001 },
  { name: 'signed error: ok=false is inside the digest, so an error cannot be relabelled as success', id: 'req-3', method: 'circuitHolder', params: { tokenId: '1' }, ok: false, body: { code: 'BAD_REQUEST', message: 'circuits must be address' }, ts: 1789000002 },
  { name: 'params key order does not matter: the canonical form is the same', id: 'req-4', method: 'echo', params: { b: 2, a: 1 }, ok: true, body: { echo: { b: 2, a: 1 } }, ts: 1789000003 },
]
write('tap-21-envelope.json', {
  tap: 'TAP-21 §3.2', note,
  prefix: sig.RESPONSE_DIGEST_PREFIX,
  layout: 'keccak256( utf8("TAPI-1/resp/v2") || container(20 bytes) || keccak256(utf8(id)) || keccak256(utf8(canonicalJSON({method,params}))) || ok(1 byte: 0x01/0x00) || keccak256(utf8(canonicalJSON(body))) || ts(uint64 big-endian) )',
  container: CONTAINER,
  signerKey: SIGNER_KEY,
  signerAddress: sig.privateKeyToAddress(SIGNER_KEY),
  cases: envCases.map((c) => {
    const digest = sig.responseDigest({ container: CONTAINER, id: c.id, method: c.method, params: c.params, ok: c.ok, body: c.body, ts: c.ts })
    // TAP-21 §3.3: the signature is an EIP-191 personal_sign over the 32-byte digest. / 签名是对 32 字节摘要的 EIP-191 personal_sign。
    const personal = sig.personalDigest(digest)
    const signature = sig.signDigest(personal, SIGNER_KEY)
    return {
      ...c,
      intermediate: {
        canonicalRequest: canonicalJSON({ method: c.method, params: c.params }),
        keccakId: k(c.id),
        keccakRequest: k(canonicalJSON({ method: c.method, params: c.params })),
        canonicalBody: canonicalJSON(c.body),
        keccakBody: k(canonicalJSON(c.body)),
      },
      digest: toHex(digest),
      personalDigest: toHex(personal),
      sig: signature,
      recoversTo: sig.recoverAddress(personal, signature),
    }
  }),
})

// ---------- TAP-20 delegation ----------
const delCases = [
  { name: 'holder authorises a hot signer for 30 days', container: CONTAINER, signer: sig.privateKeyToAddress(SIGNER_KEY), expires: 1789000000 + 30 * 86400 },
  { name: 'a different signer gives a different digest', container: CONTAINER, signer: '0x000000000000000000000000000000000000dEaD', expires: 1789000000 + 30 * 86400 },
]
write('tap-20-delegation.json', {
  tap: 'TAP-20 §3.4', note,
  domain: { name: 'TapeAPI', version: '1', chainId: CHAIN_ID, verifyingContract: HUB, comment: 'The delegation domain is anchored on the DeWebHub, not on any contract of ours: that is what lets a free service exist with none of our contracts deployed.' },
  typeHash: 'Delegation(address container,address signer,uint64 expires)',
  holderKey: HOLDER_KEY,
  holderAddress: sig.privateKeyToAddress(HOLDER_KEY),
  cases: delCases.map((c) => {
    const digest = sig.delegationDigest(CHAIN_ID, HUB, c)
    const signature = sig.signDigest(digest, HOLDER_KEY)
    return { ...c, digest: toHex(digest), sig: signature, recoversTo: sig.recoverAddress(digest, signature) }
  }),
})

// ---------- TAP-20 §3.10 manifest content signature (OPTIONAL, security 1.1) ----------
// The holder signs keccak256(UTF-8(canonicalJSON(manifest without contentSig))) as ManifestContent(container, contentHash)
// in the delegation's domain. / 持有人在委托的域中签署 ManifestContent(container, contentHash)。
{
  const signer = sig.privateKeyToAddress(SIGNER_KEY)
  const dsig = sig.signDigest(sig.delegationDigest(CHAIN_ID, HUB, { container: CONTAINER, signer, expires: 1789000000 + 30 * 86400 }), HOLDER_KEY)
  const base = {
    tapeapi: '0.1', name: 'Content-signed service', circuits: '0x50a994e71615474b55559ff4f500928fbc339dd9', tokenId: '4246',
    container: CONTAINER, signer, delegation: { expires: 1789000000 + 30 * 86400, sig: dsig },
    endpoints: { live: ['https://api.example.com/tapeapi/v1'], async: false },
    methods: [{ name: 'ping', priceBEM: '0', params: {}, returns: { pong: 'boolean' } }],
  }
  const swapped = { ...base, endpoints: { live: ['https://attacker.example/tapeapi/v1'], async: false } }
  const one = (name, manifest) => {
    const canonical = canonicalJSON(manifest)
    const contentHash = toHex(sig.manifestContentHash(manifest))
    const structHash = toHex(sig.hashManifestContent({ container: CONTAINER, contentHash }))
    const digest = sig.manifestContentDigest(CHAIN_ID, HUB, { container: CONTAINER, contentHash })
    const signature = sig.signDigest(digest, HOLDER_KEY)
    return { name, manifest, canonical, contentHash, structHash, digest: toHex(digest), sig: signature, recoversTo: sig.recoverAddress(digest, signature), published: { ...manifest, contentSig: signature } }
  }
  const a = one('holder signs the content of a manifest', base)
  const b = one('another endpoint is another content hash', swapped)
  write('tap-20-content.json', {
    tap: 'TAP-20 §3.10 (OPTIONAL)', note,
    domain: { name: 'TapeAPI', version: '1', chainId: CHAIN_ID, verifyingContract: HUB, comment: 'The TAP-20 delegation domain; the type name differs, so a delegation and a content signature can never be taken for each other.' },
    typeHash: sig.MANIFEST_CONTENT_TYPE,
    field: sig.MANIFEST_CONTENT_FIELD,
    contentHashRule: 'keccak256(UTF-8(canonicalJSON(M))) where M is the published manifest object with its top-level contentSig member removed (TAP-21 §3.3 canonical JSON)',
    holderKey: HOLDER_KEY,
    holderAddress: sig.privateKeyToAddress(HOLDER_KEY),
    cases: [a, b],
    // Moving a's signature onto b's content: it recovers to some other address, so a client refuses it.
    // 把 a 的签名搬到 b 的内容上：恢复出别的地址，客户端因此拒绝。
    moved: { sig: a.sig, content: b.name, recoversTo: sig.recoverAddress(sig.manifestContentDigest(CHAIN_ID, HUB, { container: CONTAINER, contentHash: b.contentHash }), a.sig) },
  })
}

// ---------- TAP-22 voucher ----------
const vCases = [
  { name: 'first voucher on a channel', consumer: sig.privateKeyToAddress(CONSUMER_KEY), provider: CONTAINER, cumulative: '10000', expires: 1789003600 },
  { name: 'cumulative, not incremental: the second voucher carries the running total', consumer: sig.privateKeyToAddress(CONSUMER_KEY), provider: CONTAINER, cumulative: '20000', expires: 1789003600 },
  { name: 'same figures on a different channel produce a different digest', consumer: sig.privateKeyToAddress(CONSUMER_KEY), provider: '0x000000000000000000000000000000000000BEEF', cumulative: '10000', expires: 1789003600 },
]
write('tap-22-voucher.json', {
  tap: 'TAP-22 §3.1', note,
  domain: { name: 'TapeAPIEscrow', version: '1', chainId: CHAIN_ID, verifyingContract: ESCROW },
  typeHash: 'Voucher(address consumer,address provider,uint256 cumulative,uint64 expires)',
  consumerKey: CONSUMER_KEY,
  consumerAddress: sig.privateKeyToAddress(CONSUMER_KEY),
  cases: vCases.map((c) => {
    const digest = sig.voucherDigest(CHAIN_ID, ESCROW, c)
    const signature = sig.signDigest(digest, CONSUMER_KEY)
    return { ...c, digest: toHex(digest), sig: signature, recoversTo: sig.recoverAddress(digest, signature) }
  }),
})

// ---------- TAP-23 §6: two providers, one attested read ----------
// Two TEST keys (public, never to hold anything) sign TAP-21 envelopes answering the §6 example request. The agreeing
// values are real Ethereum state, read 2026-09-28 (read-only) and identical on dRPC, Tenderly, Alchemy (Blast) and MEV
// Blocker: block 20000000's hash and state root, and USDT totalSupply() evaluated at that hash. The counterexamples change
// one compared field on provider B, so a client MUST reject them with ATTEST_DISAGREE (§3.4).
// 两把**测试密钥**（公开，绝不持有任何东西）对 §6 的示例请求签发 TAP-21 信封。一致的那组数值是真实的以太坊状态，2026-09-28
// 只读读取，dRPC、Tenderly、Alchemy（Blast）与 MEV Blocker 四家一致：区块 20000000 的哈希与状态根，以及在该哈希上求值的
// USDT totalSupply()。反例只改提供者 B 的一个比较字段，客户端 MUST 以 ATTEST_DISAGREE 拒绝（§3.4）。
{
  const PROVIDER_A_KEY = '0x' + '44'.repeat(32), PROVIDER_B_KEY = '0x' + '55'.repeat(32)
  const providers = [
    { tag: 'A', container: '0x00000000000000000000000000000000000a77e1', signerKey: PROVIDER_A_KEY, signerAddress: sig.privateKeyToAddress(PROVIDER_A_KEY), endpoint: 'https://attest-a.example/tapeapi/v1' },
    { tag: 'B', container: '0x00000000000000000000000000000000000a77e2', signerKey: PROVIDER_B_KEY, signerAddress: sig.privateKeyToAddress(PROVIDER_B_KEY), endpoint: 'https://attest-b.example/tapeapi/v1' },
  ]
  const descriptor = {
    name: 'read', priceBEM: '0',
    params: { chainId: 'number', call: 'object', block: 'string|number' },
    returns: { chainId: 'number', blockNumber: 'number', blockHash: 'bytes32', result: 'bytes' },
    attestedRead: { kind: 'eth_call', chains: [1] },
  }
  const request = { id: 'tap23-vector-1', method: 'read', params: { chainId: 1, call: { to: '0xdAC17F958D2ee523a2206206994597C13D831ec7', data: '0x18160ddd' }, block: 20000000 } }
  const ethereum = {
    chainId: 1, blockNumber: 20000000,
    blockHash: '0xd24fd73f794058a3807db926d8898c6481e902b7edb91ce0d479d6760f276183',
    stateRoot: '0x68421c2c599dc31396a09772a073fb421c4bd25ef1462914ef13e5dfa2d31c23',
    result: '0x00000000000000000000000000000000000000000000000000b8bc8118ccdd50',
    readFrom: ['eth.drpc.org', 'mainnet.gateway.tenderly.co', 'eth-mainnet.public.blastapi.io', 'rpc.mevblocker.io'],
    readOn: '2026-09-28',
  }
  const honest = { chainId: 1, blockNumber: 20000000, blockHash: ethereum.blockHash, result: ethereum.result }
  const TS = 1789000000
  const envelopeOf = (p, result, ts) => {
    const digest = sig.responseDigest({ container: p.container, id: request.id, method: request.method, params: request.params, ok: true, body: result, ts })
    const signature = sig.signResponse({ container: p.container, id: request.id, method: request.method, params: request.params, ok: true, body: result, ts }, p.signerKey)
    return { envelope: { id: request.id, ok: true, result, container: p.container, ts, sig: signature }, digest: toHex(digest), personalDigest: toHex(sig.personalDigest(digest)), recoversTo: sig.recoverAddress(sig.personalDigest(digest), signature) }
  }
  const cases = [
    { name: 'agree: both providers return the same block and bytes', expect: 'agree', a: honest, b: honest },
    { name: 'agree: stateRoot is compared only when both carry it (§3.4 step 4)', expect: 'agree', a: { ...honest, stateRoot: ethereum.stateRoot }, b: honest },
    { name: 'disagree: B signs a result one unit higher', expect: 'ATTEST_DISAGREE', a: honest, b: { ...honest, result: '0x00000000000000000000000000000000000000000000000000b8bc8118ccdd51' } },
    { name: 'disagree: B names another hash for block 20000000 (made up, not a real block)', expect: 'ATTEST_DISAGREE', a: honest, b: { ...honest, blockHash: '0x' + 'ee'.repeat(32) } },
    { name: 'disagree: both carry a stateRoot and they differ (made up for B)', expect: 'ATTEST_DISAGREE', a: { ...honest, stateRoot: ethereum.stateRoot }, b: { ...honest, stateRoot: '0x' + 'dd'.repeat(32) } },
  ]
  write('tap-23-attested.json', {
    tap: 'TAP-23 §3.3, §3.4, §6', note,
    testKeys: 'signerKey values are TEST KEYS: public, deterministic, and never to be used for anything real. / signerKey 是测试密钥：公开、确定，绝不用于任何真实用途。',
    compared: 'Two envelopes agree iff chainId, blockNumber, blockHash and result are byte-identical; stateRoot is compared only when both carry it. Any disagreement among verified envelopes is ATTEST_DISAGREE, never a majority. / 两个信封一致当且仅当 chainId、blockNumber、blockHash、result 逐字节相同；stateRoot 仅在双方都有时比较。',
    envelopeDigest: 'TAP-21 §3.3 v2 digest over the request below, the provider container, ok = true and the result; signed with EIP-191 personal_sign',
    providers, descriptor, request, ethereum,
    cases: cases.map((c) => ({ name: c.name, expect: c.expect, a: envelopeOf(providers[0], c.a, TS), b: envelopeOf(providers[1], c.b, TS + 1) })),
  })
}
console.log('done')

// ---------- TAP-26 channel ----------
{
  const channel = await import('../sdk/src/channel.js')   // the implementation module: _keySchedule, toHex / 实现模块
  const { x25519, ed25519 } = await import('@noble/curves/ed25519')
  const seq = (label) => { let n = 0; return (len) => { const out = new Uint8Array(len); for (let i = 0; i < len; i++) out[i] = (label.charCodeAt(i % label.length) + 17 * i + 31 * n) & 0xff; n++; return out } }
  const sA = new Uint8Array(32).map((_, i) => (0xa1 + i) & 0xff), sB = new Uint8Array(32).map((_, i) => (0xb2 + 3 * i) & 0xff)
  const A = { container: '0x0000000000000000000000000000000000000A11', chainId: 56 }
  const B = { container: '0x0000000000000000000000000000000000000B0B', chainId: 56 }
  const NOW = 1789000000
  const { invite, pending } = channel.createInvite({ self: { ...A, staticSecret: sA }, peer: { ...B, staticPublic: x25519.getPublicKey(sB) }, relays: [{ url: 'https://relay.example/tapeapi/v1', container: '0x3e1a3e1a3e1a3e1a3e1a3e1a3e1a3e1a3e1a3e1a' }], ttlS: 600, now: NOW, random: seq('initiator') })
  const eA = seq('initiator'); eA(16); const eAsecret = eA(32)             // same draws createInvite made / 与 createInvite 抽取的相同
  const eBsecret = seq('responder')(32)
  const { accept, session: bob } = channel.acceptInvite({ self: { ...B, staticSecret: sB }, peer: { ...A, staticPublic: x25519.getPublicKey(sA) }, invite, now: NOW, random: seq('responder') })
  const { ready, session: alice } = channel.completeInvite(pending, accept, { now: NOW })
  bob.confirm(ready, { now: NOW })
  const hex = channel.toHex
  const frames = []
  for (const [who, s, text] of [['initiator', alice, 'hello from A'], ['initiator', alice, ''], ['responder', bob, 'hello from B'], ['initiator', alice, '中文 😀']]) {
    frames.push({ from: who, plaintext: text, frame: hex(s.seal(text)) })
  }
  const SA = x25519.getPublicKey(sA), SB = x25519.getPublicKey(sB), EA = x25519.getPublicKey(eAsecret), EB = x25519.getPublicKey(eBsecret)
  const ks = channel._keySchedule({
    cid: channel.fromHex(invite.cid, 16), epA: channel.endpointBytes(A.container), epB: channel.endpointBytes(B.container),
    SA, SB, EA, EB, exp: invite.exp, ih: channel.inviteHash(invite),
    dh1: x25519.getSharedSecret(eAsecret, SB), dh2: x25519.getSharedSecret(sA, EB), dh3: x25519.getSharedSecret(eAsecret, EB),
  })
  const { hkdf } = await import('@noble/hashes/hkdf'); const { sha256 } = await import('@noble/hashes/sha256')
  const ikmV = new Uint8Array([...x25519.getSharedSecret(eAsecret, SB), ...x25519.getSharedSecret(sA, EB), ...x25519.getSharedSecret(eAsecret, EB)])
  const okmV = hkdf(sha256, ikmV, ks.th, new TextEncoder().encode('TAP-26/keys/v1'), 128)
  const okmSlice = (o) => okmV.slice(o, o + 32)
  write('tap-26-channel.json', {
    tap: 'TAP-26', note,
    layout: {
      endpoint: 'uint32(0) || uint64(chainId) || container   (32 bytes, exactly TAP-10)',
      transcript: 'sha256( "TAP-26/transcript/v1" || cid(16) || endpointA || endpointB || SA || SB || EA || EB || uint64be(exp) || inviteHash ), inviteHash = sha256(utf8(canonicalJSON(invite)))',
      ikm: 'DH(eA,SB) || DH(sA,EB) || DH(eA,EB)',
      keys: 'HKDF-SHA256(ikm, salt = transcript, info = "TAP-26/keys/v1", 128) = kAB || kBA || cA || cB',
      confirm: 'HMAC-SHA256(cA, "TAP-26/confirm/initiator" || transcript), HMAC-SHA256(cB, "TAP-26/confirm/responder" || transcript)',
      frame: 'uint64be(seq) || ChaCha20-Poly1305(key, nonce = 0x00000000 || uint64be(seq), aad = "TAP-26/frame/v1" || cid || dir || uint64be(seq)); dir 0 = initiator->responder, 1 = responder->initiator',
      rooms: 'sha256( "TAP-26/room/v1" || cid || dir ) with dir 0 = to initiator, 1 = to responder',
    },
    initiator: { ...A, staticSecret: hex(sA), staticPublic: hex(SA), ephemeralSecret: hex(eAsecret), ephemeralPublic: hex(EA) },
    responder: { ...B, staticSecret: hex(sB), staticPublic: hex(SB), ephemeralSecret: hex(eBsecret), ephemeralPublic: hex(EB) },
    invite, accept, ready,
    intermediate: {
      endpointA: hex(channel.endpointBytes(A.container)), endpointB: hex(channel.endpointBytes(B.container)),
      dh1: hex(x25519.getSharedSecret(eAsecret, SB)), dh2: hex(x25519.getSharedSecret(sA, EB)), dh3: hex(x25519.getSharedSecret(eAsecret, EB)),
      inviteHash: hex(channel.inviteHash(invite)), transcript: hex(ks.th), kAB: hex(ks.kAB), kBA: hex(ks.kBA), cA: hex(okmSlice(64)), cB: hex(okmSlice(96)),
      confirmInitiator: hex(ks.confirmA), confirmResponder: hex(ks.confirmB),
      rooms: channel.roomsFor(invite.cid),
    },
    frames,
  })

  // ---------- TAP-26 §3.1 / §3.2: channel identity authorisation, inbox room, sealed invite ----------
  const edA = new Uint8Array(32).map((_, i) => (0xc3 + 5 * i) & 0xff)
  const inboxA = { relays: [{ url: 'https://relay.example/tapeapi/v1', container: '0x3e1a3e1a3e1a3e1a3e1a3e1a3e1a3e1a3e1a3e1a' }] }
  const keysA = { container: CONTAINER, x25519: toHex(x25519.getPublicKey(sA)), ed25519: toHex(ed25519.getPublicKey(edA)), inbox: inboxA, issued: 1789000000, expires: 1790000000 }
  const keysDigest = sig.channelKeysDigest(CHAIN_ID, HUB, keysA)
  const keysSig = sig.signDigest(keysDigest, HOLDER_KEY)
  const sealRandom = seq('inbox')
  const sealed = channel.sealInvite(invite, { to: { ...B, staticPublic: x25519.getPublicKey(sB) }, random: sealRandom })
  const sr = seq('inbox'); const sealE = sr(32); const sealN = sr(24)
  write('tap-26-identity.json', {
    tap: 'TAP-26 §3.1, §3.2', note,
    channelKeys: {
      domain: { name: 'TapeAPI', version: '1', chainId: CHAIN_ID, verifyingContract: HUB },
      typeHash: sig.CHANNEL_KEYS_TYPE,
      holderKey: HOLDER_KEY, holderAddress: sig.privateKeyToAddress(HOLDER_KEY),
      ed25519Secret: toHex(edA),
      keys: { ...keysA, inboxHash: toHex(sig.channelInboxHash(inboxA)) }, digest: toHex(keysDigest), sig: keysSig, recoversTo: sig.recoverAddress(keysDigest, keysSig),
    },
    inbox: { layout: 'sha256( "TAP-26/inbox/v1" || endpoint(container, chainId) )', container: B.container, chainId: 56, room: channel.inboxRoom(B.container, 56) },
    inboxHashLayout: 'keccak256( utf8( canonicalJSON({ relays: [{ url, container }], bus? }) ) ), signed as ChannelKeys.inbox',
    sealedInvite: {
      layout: '0x03 || E(32) || N(24) || XChaCha20-Poly1305(K, N, aad = "TAP-26/inbox/v1" || E || room).encrypt(utf8(canonicalJSON(invite))), K = HKDF-SHA256(X25519(e, R), salt = "TAP-26/inbox/v1", info = E || R || room, 32)',
      recipientSecret: toHex(sB), recipientContainer: B.container, recipientChainId: 56, ephemeralSecret: toHex(sealE), nonce: toHex(sealN),
      invite, wire: toHex(sealed),
    },
  })

  // ---------- TAP-27 group: one epoch of three members, and two messages ----------
  const G = await import('../sdk/src/group.js')
  const { sha256: G_sha256 } = await import('@noble/hashes/sha256')
  const idOf = (tag) => { const r = seq(tag); const xs = r(32), es = r(32); return { x25519: { secretKey: xs, publicKey: x25519.getPublicKey(xs) }, ed25519: { secretKey: es, publicKey: ed25519.getPublicKey(es) } } }
  const people = ['owner', 'member-1', 'member-2'].map((tag, i) => ({ tag, container: '0x' + (0xa11 + i).toString(16).padStart(40, '0'), chainId: 56, identity: idOf(tag) }))
  const ent = (p) => ({ container: p.container, chainId: 56, x25519: toHex(p.identity.x25519.publicKey), ed25519: toHex(p.identity.ed25519.publicKey) })
  const groupRandom = seq('group')
  const T0 = 1789000000          // fixed clock (Unix seconds): issued and seq derive from it / 固定时钟（Unix 秒）：issued 与 seq 由它导出
  const { group: gOwner, epochWire } = await G.createGroup({ self: people[0], identity: people[0].identity, members: [ent(people[1]), ent(people[2])], relays: [{ url: 'https://relay.example/tapeapi/v1', container: '0x3e1a3e1a3e1a3e1a3e1a3e1a3e1a3e1a3e1a3e1a' }], verifyMember: 'trust-roster', random: groupRandom, clock: () => T0 })
  const gr = seq('group'); const gidB = gr(16), Kb = gr(32), eb = gr(32), Nb = gr(24)          // the same draws, in order / 同样的抽取顺序
  const g1 = G.joinGroup({ self: people[1], identity: people[1].identity, invite: { gid: gOwner.gid, owner: { container: people[0].container, chainId: 56 } }, ownerKeys: ent(people[0]), clock: () => T0 })
  await g1.acceptEpoch(epochWire, { verifyMember: 'trust-roster' })
  const nonceOf = (tag) => { const r = seq(tag); return () => r(24) }
  const msgs = [
    { sender: 0, plaintext: 'hello, group', nonce: seq('msg-0')(24), wire: gOwner.seal('hello, group', { random: nonceOf('msg-0') }) },
    { sender: 1, plaintext: '你好 from member 1', nonce: seq('msg-1')(24), wire: g1.seal('你好 from member 1', { random: nonceOf('msg-1') }) },
  ]
  write('tap-27-group.json', {
    tap: 'TAP-27', note,
    layout: {
      epochHeader: '0x04 || gid(16) || uint64be(epoch) || E(32) || N(24) || commit(32) || count(1); commit = sha256("TAP-27/commit/v1" || K)',
      rosterMembers: 'exactly { container (lowercase), chainId, x25519, ed25519 (lowercase 0x hex) }; roster.issued = unix seconds; prev = sha256(roster plaintext bytes of epoch - 1)',
      slot: 'XChaCha20-Poly1305(HKDF-SHA256(X25519(e, R), salt = "TAP-27/wrap/v1", info = E || R || gid || uint64be(epoch), 32), N, aad = header).encrypt(K)   (48 bytes, no fingerprint)',
      epochWire: 'header || slots || uint32be(len) || XChaCha20-Poly1305(K, N, aad = header || slots).encrypt(canonicalJSON(roster)) || Ed25519(owner, "TAP-27/epoch/v1" || everything before)',
      message: 'header = 0x05 || gid || uint64be(epoch) || uint32be(sender) || uint64be(seq) || nonce(24, random); ct = XChaCha20-Poly1305(senderKey, nonce, aad = header).encrypt(pt); wire = header || ct || Ed25519(sender, "TAP-27/msg/v1" || header || ct)',
      senderKey: 'HKDF-SHA256(K, salt = gid || uint64be(epoch), info = "TAP-27/sender/v1" || uint32be(sender), 32)',
    },
    members: people.map((p) => ({ tag: p.tag, container: p.container, chainId: 56, x25519Secret: toHex(p.identity.x25519.secretKey), ed25519Secret: toHex(p.identity.ed25519.secretKey), x25519: toHex(p.identity.x25519.publicKey), ed25519: toHex(p.identity.ed25519.publicKey) })),
    gid: toHex(gidB), epoch: 0, K: toHex(Kb), ephemeralSecret: toHex(eb), nonce: toHex(Nb),
    roster: gOwner.roster,
    epochWire: toHex(epochWire),
    senderKeys: [0, 1, 2].map((i) => toHex(G.senderKey(Kb, gidB, 0, i))),
    messages: msgs.map((m) => ({ sender: m.sender, seq: (BigInt(T0 * 1000) << 16n).toString(), nonce: toHex(m.nonce), plaintext: m.plaintext, wire: toHex(m.wire) })),
  })

  // ---------- TAP-27 §3.8 format 2 (Experimental): the same three members, epochs 0 and 1, two messages ----------
  // A separate file, so the format-1 vectors above stay byte for byte what they were. / 单独成文件，上面格式 1 的向量逐字节不变。
  const draws = []
  const rec = (r) => (n) => { const b = r(n); draws.push(b.slice()); return b }   // a copy: the builder zeroes e after use / 存副本：构造器用完会把 e 清零
  const random2 = rec(seq('group-v2'))
  const relays2 = [{ url: 'https://relay.example/tapeapi/v1', container: '0x3e1a3e1a3e1a3e1a3e1a3e1a3e1a3e1a3e1a3e1a' }]
  const bus2 = '0xcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcb'
  const { group: o2, epochWire: ew0 } = await G.createGroup({ format: 2, self: people[0], identity: people[0].identity, members: [ent(people[1]), ent(people[2])], relays: relays2, bus: bus2, verifyMember: 'trust-roster', random: random2, clock: () => T0 })
  const roster0 = o2._held().rosterBytes
  const up1 = await o2.rotate({ verifyMember: 'trust-roster' })
  const roster1 = o2._held().rosterBytes
  const [gid2, K0, e0, N0, K1, e1, N1] = draws
  const m1 = G.joinGroup({ self: people[1], identity: people[1].identity, invite: { gid: o2.gid, owner: { container: people[0].container, chainId: 56 }, format: 2 }, ownerKeys: ent(people[0]), verifyMember: 'trust-roster', clock: () => T0 })
  await m1.acceptEpoch(ew0)
  await m1.acceptEpoch(up1.epochWire)
  const msgs2 = [
    { sender: 0, plaintext: 'hello, format 2', nonce: seq('msg2-0')(24), wire: o2.seal('hello, format 2', { random: nonceOf('msg2-0') }) },
    { sender: 1, plaintext: '第二版 from member 1', nonce: seq('msg2-1')(24), wire: m1.seal('第二版 from member 1', { random: nonceOf('msg2-1') }) },
  ]
  const ef = (n) => '54470200' + n.toString(16).padStart(8, '0')
  write('tap-27-group-v2.json', {
    tap: 'TAP-27 §3.8 (format 2, Experimental)', note,
    layout: {
      epochField: 'uint32be(0x54470200) || uint32be(n): the high half is the format-2 mark, which format 1 requires to be zero',
      epochHeader: '0x04 || gid(16) || epochField(8) || E(32) || N(24) || commit(32) || uint16be(count); commit = sha256("TAP-27/commit/v2" || K)',
      slot: 'XChaCha20-Poly1305(HKDF-SHA256(X25519(e, R), salt = "TAP-27/wrap/v2", info = E || R || gid || epochField, 32), N, aad = header).encrypt(K)   (48 bytes, no fingerprint)',
      roster: '"TGR2" || uint64be(issued) || prev(32) || uint16be(count) || count x ( container(20) || uint32be(chainId) || ed25519(32) ) || uint16be(L) || utf8(canonicalJSON({ relays, bus? }))(L); prev = sha256(roster bytes of epoch n - 1) or 32 zero bytes',
      epochWire: 'header || slots || uint32be(len) || XChaCha20-Poly1305(K, N, aad = header || slots).encrypt(roster) || Ed25519(owner, "TAP-27/epoch/v2" || everything before)',
      message: 'header = 0x05 || gid || epochField(8) || uint32be(sender) || uint64be(seq) || nonce(24, random); ct = XChaCha20-Poly1305(senderKey, nonce, aad = header).encrypt(pt); wire = header || ct || Ed25519(sender, "TAP-27/msg/v2" || header || ct)',
      senderKey: 'HKDF-SHA256(K, salt = gid || epochField, info = "TAP-27/sender/v2" || uint32be(sender), 32)',
      invite: 'the format-1 invite object plus "format": 2',
    },
    members: people.map((p) => ({ tag: p.tag, container: p.container, chainId: 56, x25519Secret: toHex(p.identity.x25519.secretKey), ed25519Secret: toHex(p.identity.ed25519.secretKey), x25519: toHex(p.identity.x25519.publicKey), ed25519: toHex(p.identity.ed25519.publicKey) })),
    gid: toHex(gid2), issued: T0, relays: relays2, bus: bus2,
    epochs: [
      { epoch: 0, epochField: ef(0), K: toHex(K0), ephemeralSecret: toHex(e0), nonce: toHex(N0), prev: '00'.repeat(32), roster: toHex(roster0), epochWire: toHex(ew0) },
      { epoch: 1, epochField: ef(1), K: toHex(K1), ephemeralSecret: toHex(e1), nonce: toHex(N1), prev: toHex(G_sha256(roster0)).slice(2), roster: toHex(roster1), epochWire: toHex(up1.epochWire) },
    ],
    senderKeys: [0, 1, 2].map((i) => toHex(G.senderKeyV2(K1, gid2, 1, i))),
    // seq as sent: a member that installed two epochs at one clock reading counts on from the first (§3.4) / 按实际发送的 seq
    messages: msgs2.map((m) => ({ epoch: 1, sender: m.sender, seq: new DataView(m.wire.buffer, m.wire.byteOffset + 29, 8).getBigUint64(0).toString(), nonce: toHex(m.nonce), plaintext: m.plaintext, wire: toHex(m.wire) })),
    format1Refuses: 'A format-1 receiver refuses every wire above: the epoch field exceeds 2^32 - 1 (TAP-27 §3.3), and the reference format-1 parser also reads count = 0 at offset 113. Reference code: GROUP_INVALID.',
  })
}

// ---------- Merkle proofs (TAP-20 §3.2, informative; security 1.2) ----------
// Two parts. `trie`: cases copied from the Ethereum trie tests (their roots are ethereum/tests' own), with proofs this
// repository's test-only builder made (sdk/test/helpers/trie.mjs); a checker rebuilds each root from `in` itself and
// verifies each proof, including keys absent from the trie and embedded nodes. `mainnet`: the eth_getProof answers of a
// real resolution of 11.1013.tape (sdk/test/fixtures/mainnet-11-1013-proof.json), the values they prove against the
// block's stateRoot, and single-byte changes that every checker must refuse.
// 两部分。`trie`：摘自以太坊 trie 测试的用例（根值是 ethereum/tests 自己的），证明由本仓库仅供测试的构建器生成；核验方自行由 `in` 重建根，
// 并核验每个证明（包括树中不存在的键与内嵌节点）。`mainnet`：11.1013.tape 一次真实解析的 eth_getProof 回答、它们对照区块 stateRoot 证明的值，
// 以及每个核验方都必须拒绝的单字节改动。
{
  const { readFileSync } = await import('node:fs')
  const { keccak_256 } = await import('@noble/hashes/sha3')
  const { buildTrie, trieBytes } = await import('../sdk/test/helpers/trie.mjs')
  const { verifyAccountProof, verifyMptProof, STORAGE } = await import('../sdk/src/proof.js')
  const abi = await import('../sdk/src/abi.js')
  const ET = JSON.parse(readFileSync(new URL('../sdk/test/fixtures/ethereum-trie-tests.json', import.meta.url), 'utf8'))
  const FX = JSON.parse(readFileSync(new URL('../sdk/test/fixtures/mainnet-11-1013-proof.json', import.meta.url), 'utf8'))
  const hexOf = (b) => (b === null ? null : toHex(b))
  const trie = []
  for (const [file, cases] of Object.entries(ET.files)) {
    const secure = /secure/i.test(file)
    for (const c of cases) {
      const pairs = Object.entries(c.in).map(([k, v]) => [trieBytes(k), trieBytes(v)])
      const t = buildTrie(pairs, { secure })
      if (t.root !== c.root) throw new Error(`trie ${file}/${c.name}: built ${t.root}, ethereum/tests says ${c.root}`)
      const keyOf = (k) => (secure ? keccak_256(k) : k)
      const asks = [...pairs.map(([k]) => k), trieBytes('0xdeadbeefcafe'), trieBytes('do'), trieBytes('dogz')]
      const seen = new Set()
      const proofs = []
      for (const k of asks) {
        if (seen.has(toHex(k))) continue
        seen.add(toHex(k))
        const proof = t.proof(k)
        const value = verifyMptProof(t.root, keyOf(k), proof, { secure })
        proofs.push({ key: toHex(k), path: toHex(keyOf(k)), value: hexOf(value), proof })
      }
      trie.push({ file, name: c.name, secure, in: c.in, root: c.root, proofs })
    }
  }
  const accounts = [...FX.getProof, ...FX.absent].map((g) => {
    const r = verifyAccountProof(FX.block.stateRoot, g.address, g.slots, g.answer)
    return {
      address: g.address, slots: g.slots, answer: { accountProof: g.answer.accountProof, storageHash: g.answer.storageHash, storageProof: g.answer.storageProof.map((s) => ({ key: s.key, value: s.value, proof: s.proof })) },
      expect: { exists: r.account.exists, storageRoot: r.account.storageRoot, codeHash: r.account.codeHash, values: Object.fromEntries([...r.values].map(([k, v]) => ['0x' + k.toString(16), '0x' + v.toString(16)])) },
    }
  })
  // First, middle and last byte of every node: a checker must refuse each change (xor 0x01) / 每个节点的首、中、末字节
  const mutations = []
  accounts.forEach((a, ai) => {
    const lists = [['accountProof', a.answer.accountProof], ...a.answer.storageProof.map((s, si) => [`storageProof.${si}`, s.proof])]
    for (const [list, nodes] of lists) nodes.forEach((n, ni) => { const len = (n.length - 2) / 2; for (const byte of [...new Set([0, len >> 1, len - 1])]) mutations.push({ account: ai, list, node: ni, byte, xor: 1 }) })
  })
  write('tap-20-proof.json', {
    tap: 'TAP-20 §3.2 (informative): Merkle proofs of chain state, EIP-1186 eth_getProof against a stateRoot', note,
    rules: {
      rlp: 'canonical only: a single byte below 0x80 is not wrapped, lengths have no leading zeros, the long form starts at 56 bytes, nothing follows the item',
      trie: 'Yellow Paper appendix D: the root node is always referenced by hash; a child is a 32-byte hash or an embedded node whose RLP is under 32 bytes; hex-prefix flags 0-3 (odd lengths carry a nibble, even ones a zero pad); a proof with nodes left unused is refused; a key shown absent (an empty branch slot, or a leaf or extension whose path diverges) has no value',
      account: 'state trie key keccak256(address); leaf value RLP([nonce, balance, storageRoot, codeHash]); an absent account has the empty storage root ' + '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
      storage: 'storage trie (root = the account storageRoot) key keccak256(uint256 slot as 32 bytes); leaf value RLP(the word without leading zeros); absent = 0',
      layouts: { fileInfoSize: 'low 32 bits of keccak256(keccak256(path) || uint256(keccak256(uint256(container) || uint256(1)) + 2)) + 1', fileInfoSha256: 'the same base + 2', ownerOf: 'keccak256(uint256(tokenId) || uint256(0x80bb2b638cc20bc4d0a60d66940f3ab4a00c1d7b313497ca82fb0b4ab0079300 + 2))', cpuAt: 'length at slot 6, element n at keccak256(uint256(6)) + n', isCPU: 'keccak256(uint256(circuits) || uint256(7))' },
    },
    trie,
    mainnet: {
      source: FX.source, chainId: FX.chainId, block: FX.block,
      layoutCheck: { container: FX.container, path: '.well-known/tapeapi.json', tokenId: '11', processor: '1013', fileInfo: Object.fromEntries(Object.entries(STORAGE.fileInfo(FX.container, '.well-known/tapeapi.json')).map(([k, v]) => [k, '0x' + v.toString(16)])), ownerOf: '0x' + STORAGE.ownerOf(11n).toString(16), cpuAt: Object.fromEntries(Object.entries(STORAGE.cpuAt(1013n)).map(([k, v]) => [k, '0x' + v.toString(16)])), isCPU: '0x' + STORAGE.isCPU('0xe02c26c7432A7121168AA9B610DE24eCf9a1a414').toString(16) },
      // What the nodes answered by eth_call at the same block (the fixture): each proven slot must say the same.
      // 同一区块上节点 eth_call 的回答（fixture）：每个已证明的槽都必须与之一致。
      reads: (() => {
        const { decodeReturn, selector } = abi
        const call = (fn) => decodeReturn(fn, FX.calls.find((c) => c.data.startsWith(selector(fn))).result)
        const info = call('fileInfo')
        return { ownerOf: call('ownerOf').toLowerCase(), cpuAt: call('cpuAt').toLowerCase(), isCPU: call('isCPU'), size: Number(info.size), sha256Hash: info.sha256Hash.toLowerCase() }
      })(),
      accounts,
      mutations,
      wrongRoot: { stateRoot: '0x' + FX.block.stateRoot.slice(2, 64) + ((parseInt(FX.block.stateRoot.slice(64), 16) ^ 1).toString(16).padStart(2, '0')), expect: 'reject every account' },
    },
  })
}
